-- transient=true
{{ config(
    materialized='table',
    transient=true,
    pre_hook=[
        "CALL DEV.LH2_EXPLOIT_DEV.SET_GLOBAL_VAR_PROC('S','OU_DETAILS_TEMP','LH2_SILVER_DEV.OU_DETAILS_TEMP','BEGIN','10')",
        "CALL DEV.LH2_EXPLOIT_DEV.WRITE_LOG_PROC()"
    ],
    post_hook=[
        "CALL DEV.LH2_EXPLOIT_DEV.SET_GLOBAL_VAR_PROC('S','OU_DETAILS_TEMP','LH2_SILVER_DEV.OU_DETAILS_TEMP','COMPLETED','90',NULL::VARCHAR,NULL::VARCHAR,NULL::TIMESTAMP_NTZ,NULL::TIMESTAMP_NTZ,(SELECT COUNT(*) FROM {{ this }}))",
        "CALL DEV.LH2_EXPLOIT_DEV.WRITE_LOG_PROC()"
    ]
) }}


-- voir pour ajouter exception à
SELECT TO_TIMESTAMP('01/01/52 00:00:00', 'DD/MM/YY HH24:MI:SS.FF9') AS HAOU_DATE_FROM, 'LS SINGAPORE' AS HAOU_NAME, TO_TIMESTAMP('08/01/15 12:31:24', 'DD/MM/YY HH24:MI:SS.FF9') AS HAOU_LAST_UPDATE_DATE, 10227 AS HAOU_LAST_UPDATED_BY, 64135079 AS HAOU_LAST_UPDATE_LOGIN, 10227 AS HAOU_CREATED_BY, TO_TIMESTAMP('08/01/15 11:05:10', 'DD/MM/YY HH24:MI:SS.FF9') AS HAOU_CREATION_DATE, 2 AS HAOU_OBJECT_VERSION_NUMBER, 0 AS HOU_BUSINESS_GROUP_ID, 99991 AS HOU_ORGANIZATION_ID, 'LS SINGAPORE' AS HOU_NAME, 'SG' AS HLA_COUNTRY, 'SGD' AS GSOB_CURRENCY_CODE, sysdate AS ROW_CREATION_DATE, sysdate AS ROW_LAST_UPDATE_DATE
