-- transient=true
{{ config(
    materialized='table',
    transient=true,
    pre_hook=[
        "CALL DEV.LH2_EXPLOIT_DEV.SET_GLOBAL_VAR_PROC('S','GL_SEGMENT2_LOCATION_TEMP','LH2_SILVER_DEV.GL_SEGMENT2_LOCATION_TEMP','BEGIN','10')",
        "CALL DEV.LH2_EXPLOIT_DEV.WRITE_LOG_PROC()"
    ],
    post_hook=[
        "CALL DEV.LH2_EXPLOIT_DEV.SET_GLOBAL_VAR_PROC('S','GL_SEGMENT2_LOCATION_TEMP','LH2_SILVER_DEV.GL_SEGMENT2_LOCATION_TEMP','COMPLETED','90',NULL::VARCHAR,NULL::VARCHAR,NULL::TIMESTAMP_NTZ,NULL::TIMESTAMP_NTZ,(SELECT COUNT(*) FROM {{ this }}))",
        "CALL DEV.LH2_EXPLOIT_DEV.WRITE_LOG_PROC()"
    ]
) }}


-- voir pour ajouter exception à
SELECT 'KOREA' AS LOCATION_GL_SEGMENT2, 101 AS CHART_OF_ACCOUNTS_ID, 'LS-Korea' AS LOCATION_GL_DESCRIPTION, 'LOC SUBSIDIARY' AS LOCATION_GL_REGROUPEMENT_VENTE, 'ASIA' AS LOCATION_GL_REGROUPEMENT_ACHAT, 'NOT AFFECTED' AS LOCATION_GL_BU_VENTE, 'segment_5' AS CLE_BU_INVOICE, TO_TIMESTAMP('01/01/52 00:00:00', 'DD/MM/YY HH24:MI:SS.FF9') AS DATE_MAJ_EXCEL, null AS COMMENTAIRES, TO_TIMESTAMP('01/01/52 00:00:00', 'DD/MM/YY HH24:MI:SS.FF9') AS CREATION_DATE, null AS CREATED_BY, null AS LAST_UPDATE_DATE, null AS LAST_UPDATED_BY, 9999999999 AS ROW_NUMBER_ID, SYSDATE AS ROW_CREATION_DATE, SYSDATE AS ROW_LAST_UPDATE_DATE
