-- transient=true
{{ config(
    materialized='table',
    transient=true,
    pre_hook=[
        "CALL DEV.LH2_EXPLOIT_DEV.SET_GLOBAL_VAR_PROC('S','STRUCTURE_RESEAU_TEMP','LH2_SILVER_DEV.STRUCTURE_RESEAU_TEMP','BEGIN','10')",
        "CALL DEV.LH2_EXPLOIT_DEV.WRITE_LOG_PROC()"
    ],
    post_hook=[
        "CALL DEV.LH2_EXPLOIT_DEV.SET_GLOBAL_VAR_PROC('S','STRUCTURE_RESEAU_TEMP','LH2_SILVER_DEV.STRUCTURE_RESEAU_TEMP','COMPLETED','90',NULL::VARCHAR,NULL::VARCHAR,NULL::TIMESTAMP_NTZ,NULL::TIMESTAMP_NTZ,(SELECT COUNT(*) FROM {{ this }}))",
        "CALL DEV.LH2_EXPLOIT_DEV.WRITE_LOG_PROC()"
    ]
) }}


-- voir pour ajouter exception à
SELECT *
   FROM (
      SELECT DISTINCT
         jrs.SALESREP_ID                     ORA_SALESREP_SALESREP_ID,
         jrs.RESOURCE_ID                     ORA_SALESREP_RESOURCE_ID,
         jrs.LAST_UPDATE_DATE                ORA_SALESREP_LAST_UPDATE_DATE,
         jrs.LAST_UPDATED_BY                 ORA_SALESREP_LAST_UPDATED_BY,
         jrs.CREATION_DATE                   ORA_SALESREP_CREATION_DATE,
         jrs.CREATED_BY                      ORA_SALESREP_CREATED_BY,
         jrs.LAST_UPDATE_LOGIN               ORA_SALESREP_LAST_UPDATE_LOGIN,
         jrs.SALES_CREDIT_TYPE_ID            ORA_SALESREP_SALES_CREDIT_TYPE_ID,
         jrs.NAME                            ORA_SALESREP_NAME,
         jrs.STATUS                          ORA_SALESREP_STATUS,
         jrs.START_DATE_ACTIVE               ORA_SALESREP_START_DATE_ACTIVE,
         jrs.END_DATE_ACTIVE                 ORA_SALESREP_END_DATE_ACTIVE,
         jrs.GL_ID_REV                       ORA_SALESREP_GL_ID_REV,
         jrs.GL_ID_FREIGHT                   ORA_SALESREP_GL_ID_FREIGHT,
         jrs.GL_ID_REC                       ORA_SALESREP_GL_ID_REC,
         jrs.SET_OF_BOOKS_ID                 ORA_SALESREP_SET_OF_BOOKS_ID,
         jrs.SALESREP_NUMBER                 ORA_SALESREP_SALESREP_NUMBER,
         jrs.ORG_ID                          ORA_SALESREP_ORG_ID,
         jrs.EMAIL_ADDRESS                   ORA_SALESREP_EMAIL_ADDRESS,
         jrs.WH_UPDATE_DATE                  ORA_SALESREP_WH_UPDATE_DATE,
         jrs.PERSON_ID                       ORA_SALESREP_PERSON_ID,
         jrs.SALES_TAX_GEOCODE               ORA_SALESREP_SALES_TAX_GEOCODE,
         jrs.SALES_TAX_INSIDE_CITY_LIMITS    ORA_SALESREP_SALES_TAX_INSIDE_CITY_LIMITS,
         jrs.OBJECT_VERSION_NUMBER           ORA_SALESREP_OBJECT_VERSION_NUMBER,
         jrs.ATTRIBUTE_CATEGORY              ORA_SALESREP_ATTRIBUTE_CATEGORY,
         jrs.ATTRIBUTE1                      ORA_SALESREP_ATTRIBUTE1,
         jrs.ATTRIBUTE2                      ORA_SALESREP_ATTRIBUTE2,
         jrs.ATTRIBUTE3                      ORA_SALESREP_ATTRIBUTE3,
         jrs.ATTRIBUTE4                      ORA_SALESREP_ATTRIBUTE4,
         jrs.ATTRIBUTE5                      ORA_SALESREP_ATTRIBUTE5,
         jrs.ATTRIBUTE6                      ORA_SALESREP_ATTRIBUTE6,
         jrs.ATTRIBUTE7                      ORA_SALESREP_ATTRIBUTE7,
         jrs.ATTRIBUTE8                      ORA_SALESREP_ATTRIBUTE8,
         jrs.ATTRIBUTE9                      ORA_SALESREP_ATTRIBUTE9,
         jrs.ATTRIBUTE10                     ORA_SALESREP_ATTRIBUTE10,
         jrs.ATTRIBUTE11                     ORA_SALESREP_ATTRIBUTE11,
         jrs.ATTRIBUTE12                     ORA_SALESREP_ATTRIBUTE12,
         jrs.ATTRIBUTE13                     ORA_SALESREP_ATTRIBUTE13,
         jrs.ATTRIBUTE14                     ORA_SALESREP_ATTRIBUTE14,
         jrs.ATTRIBUTE15                     ORA_SALESREP_ATTRIBUTE15,
         jrs.SECURITY_GROUP_ID               ORA_SALESREP_SECURITY_GROUP_ID,
         jrs.FETCH_DATE                      ORA_SALESREP_FETCH_DATE,
         jrd.ROW_ID                          ORA_RESOURCE_ROW_ID,
         jrd.CREATED_BY                      ORA_RESOURCE_CREATED_BY,
         jrd.CREATION_DATE                   ORA_RESOURCE_CREATION_DATE,
         jrd.LAST_UPDATED_BY                 ORA_RESOURCE_LAST_UPDATED_BY,
         jrd.LAST_UPDATE_DATE                ORA_RESOURCE_LAST_UPDATE_DATE,
         jrd.LAST_UPDATE_LOGIN               ORA_RESOURCE_LAST_UPDATE_LOGIN,
         jrd.CATEGORY                        ORA_RESOURCE_CATEGORY,
         jrd.CATG_MEANING                    ORA_RESOURCE_CATG_MEANING,
         jrd.RESOURCE_NUMBER                 ORA_RESOURCE_ORA_RESOURCE_NUMBER,
         jrd.SOURCE_ID                       ORA_RESOURCE_SOURCE_ID,
         jrd.ADDRESS_ID                      ORA_RESOURCE_ADDRESS_ID,
         jrd.CONTACT_ID                      ORA_RESOURCE_CONTACT_ID,
         jrd.MANAGING_EMPLOYEE_ID            ORA_RESOURCE_MANAGING_EMPLOYEE_ID,
         jrd.START_DATE_ACTIVE               ORA_RESOURCE_START_DATE_ACTIVE,
         jrd.END_DATE_ACTIVE                 ORA_RESOURCE_END_DATE_ACTIVE,
         jrd.TIME_ZONE                       ORA_RESOURCE_TIME_ZONE,
         jrd.COST_PER_HR                     ORA_RESOURCE_COST_PER_HR,
         jrd.PRIMARY_LANGUAGE                ORA_RESOURCE_PRIMARY_LANGUAGE,
         jrd.SECONDARY_LANGUAGE              ORA_RESOURCE_SECONDARY_LANGUAGE,
         jrd.SUPPORT_SITE_ID                 ORA_RESOURCE_SUPPORT_SITE_ID,
         jrd.IES_AGENT_LOGIN                 ORA_RESOURCE_IES_AGENT_LOGIN,
         jrd.SERVER_GROUP_ID                 ORA_RESOURCE_SERVER_GROUP_ID,
         jrd.ASSIGNED_TO_GROUP_ID            ORA_RESOURCE_ASSIGNED_TO_GROUP_ID,
         jrd.COST_CENTER                     ORA_RESOURCE_COST_CENTER,
         jrd.CHARGE_TO_COST_CENTER           ORA_RESOURCE_CHARGE_TO_COST_CENTER,
         jrd.COMPENSATION_CURRENCY_CODE      ORA_RESOURCE_COMPENSATION_CURRENCY_CODE,
         jrd.COMMISSIONABLE_FLAG             ORA_RESOURCE_COMMISSIONABLE_FLAG,
         jrd.HOLD_REASON_CODE                ORA_RESOURCE_HOLD_REASON_CODE,
         jrd.HOLD_PAYMENT                    ORA_RESOURCE_HOLD_PAYMENT,
         jrd.COMP_SERVICE_TEAM_ID            ORA_RESOURCE_COMP_SERVICE_TEAM_ID,
         jrd.TRANSACTION_NUMBER              ORA_RESOURCE_TRANSACTION_NUMBER,
         jrd.OBJECT_VERSION_NUMBER           ORA_RESOURCE_OBJECT_VERSION_NUMBER,
         jrd.ATTRIBUTE1                      ORA_RESOURCE_ATTRIBUTE1,
         jrd.ATTRIBUTE2                      ORA_RESOURCE_ATTRIBUTE2,
         jrd.ATTRIBUTE3                      ORA_RESOURCE_ATTRIBUTE3,
         jrd.ATTRIBUTE4                      ORA_RESOURCE_ATTRIBUTE4,
         jrd.ATTRIBUTE5                      ORA_RESOURCE_ATTRIBUTE5,
         jrd.ATTRIBUTE6                      ORA_RESOURCE_ATTRIBUTE6,
         jrd.ATTRIBUTE7                      ORA_RESOURCE_ATTRIBUTE7,
         jrd.ATTRIBUTE8                      ORA_RESOURCE_ATTRIBUTE8,
         jrd.ATTRIBUTE9                      ORA_RESOURCE_ATTRIBUTE9,
         jrd.ATTRIBUTE10                     ORA_RESOURCE_ATTRIBUTE10,
         jrd.ATTRIBUTE11                     ORA_RESOURCE_ATTRIBUTE11,
         jrd.ATTRIBUTE12                     ORA_RESOURCE_ATTRIBUTE12,
         jrd.ATTRIBUTE13                     ORA_RESOURCE_ATTRIBUTE13,
         jrd.ATTRIBUTE14                     ORA_RESOURCE_ATTRIBUTE14,
         jrd.ATTRIBUTE15                     ORA_RESOURCE_ATTRIBUTE15,
         jrd.ATTRIBUTE_CATEGORY              ORA_RESOURCE_ATTRIBUTE_CATEGORY,
         jrd.USER_ID                         ORA_RESOURCE_USER_ID,
         jrd.RESOURCE_NAME                   ORA_RESOURCE_RESOURCE_NAME,
         jrd.SOURCE_NAME                     ORA_RESOURCE_SOURCE_NAME,
         jrd.SOURCE_NUMBER                   ORA_RESOURCE_SOURCE_NUMBER,
         jrd.SOURCE_JOB_TITLE                ORA_RESOURCE_SOURCE_JOB_TITLE,
         jrd.SOURCE_EMAIL                    ORA_RESOURCE_SOURCE_EMAIL,
         jrd.SOURCE_PHONE                    ORA_RESOURCE_SOURCE_PHONE,
         jrd.SOURCE_ORG_ID                   ORA_RESOURCE_SOURCE_ORG_ID,
         jrd.SOURCE_ORG_NAME                 ORA_RESOURCE_SOURCE_ORG_NAME,
         jrd.SOURCE_ADDRESS1                 ORA_RESOURCE_SOURCE_ADDRESS1,
         jrd.SOURCE_ADDRESS2                 ORA_RESOURCE_SOURCE_ADDRESS2,
         jrd.SOURCE_ADDRESS3                 ORA_RESOURCE_SOURCE_ADDRESS3,
         jrd.SOURCE_ADDRESS4                 ORA_RESOURCE_SOURCE_ADDRESS4,
         jrd.SOURCE_CITY                     ORA_RESOURCE_SOURCE_CITY,
         jrd.SOURCE_POSTAL_CODE              ORA_RESOURCE_SOURCE_POSTAL_CODE,
         jrd.SOURCE_STATE                    ORA_RESOURCE_SOURCE_STATE,
         jrd.SOURCE_PROVINCE                 ORA_RESOURCE_SOURCE_PROVINCE,
         jrd.SOURCE_COUNTY                   ORA_RESOURCE_SOURCE_COUNTY,
         jrd.SOURCE_COUNTRY                  ORA_RESOURCE_SOURCE_COUNTRY,
         jrd.SOURCE_MGR_ID                   ORA_RESOURCE_SOURCE_MGR_ID,
         jrd.SOURCE_MGR_NAME                 ORA_RESOURCE_SOURCE_MGR_NAME,
         jrd.SOURCE_BUSINESS_GRP_ID          ORA_RESOURCE_SOURCE_BUSINESS_GRP_ID,
         jrd.SOURCE_BUSINESS_GRP_NAME        ORA_RESOURCE_SOURCE_BUSINESS_GRP_NAME,
         jrd.SOURCE_FIRST_NAME               ORA_RESOURCE_SOURCE_FIRST_NAME,
         jrd.SOURCE_MIDDLE_NAME              ORA_RESOURCE_SOURCE_MIDDLE_NAME,
         jrd.SOURCE_LAST_NAME                ORA_RESOURCE_SOURCE_LAST_NAME,
         jrd.SOURCE_CATEGORY                 ORA_RESOURCE_SOURCE_CATEGORY,
         jrd.SOURCE_STATUS                   ORA_RESOURCE_SOURCE_STATUS,
         jrd.USER_NAME                       ORA_RESOURCE_USER_NAME,
         jrd.SOURCE_OFFICE                   ORA_RESOURCE_SOURCE_OFFICE,
         jrd.SOURCE_LOCATION                 ORA_RESOURCE_SOURCE_LOCATION,
         jrd.SOURCE_MAILSTOP                 ORA_RESOURCE_SOURCE_MAILSTOP,
         jrd.SOURCE_MOBILE_PHONE             ORA_RESOURCE_SOURCE_MOBILE_PHONE,
         jrd.SOURCE_PAGER                    ORA_RESOURCE_SOURCE_PAGER,
         jrd.FETCH_DATE                      ORA_RESOURCE_FETCH_DATE,
         flv.LOOKUP_TYPE                     ORA_LOOKUP_EMR_BRANCH_AREA_MAPPING_MLS_LOOKUP_TYPE,
         flv.LANGUAGE                        ORA_LOOKUP_EMR_BRANCH_AREA_MAPPING_MLS_LANGUAGE,
         flv.LOOKUP_CODE                     ORA_LOOKUP_EMR_BRANCH_AREA_MAPPING_MLS_LOOKUP_CODE,
         flv.MEANING                         ORA_LOOKUP_EMR_BRANCH_AREA_MAPPING_MLS_MEANING,
         flv.DESCRIPTION                     ORA_LOOKUP_EMR_BRANCH_AREA_MAPPING_MLS_DESCRIPTION,
         flv.ENABLED_FLAG                    ORA_LOOKUP_EMR_BRANCH_AREA_MAPPING_MLS_ENABLED_FLAG,
         flv.START_DATE_ACTIVE               ORA_LOOKUP_EMR_BRANCH_AREA_MAPPING_MLS_START_DATE_ACTIVE,
         flv.END_DATE_ACTIVE                 ORA_LOOKUP_EMR_BRANCH_AREA_MAPPING_MLS_END_DATE_ACTIVE,
         flv.CREATED_BY                      ORA_LOOKUP_EMR_BRANCH_AREA_MAPPING_MLS_CREATED_BY,
         flv.CREATION_DATE                   ORA_LOOKUP_EMR_BRANCH_AREA_MAPPING_MLS_CREATION_DATE,
         flv.LAST_UPDATED_BY                 ORA_LOOKUP_EMR_BRANCH_AREA_MAPPING_MLS_LAST_UPDATED_BY,
         flv.LAST_UPDATE_LOGIN               ORA_LOOKUP_EMR_BRANCH_AREA_MAPPING_MLS_LAST_UPDATE_LOGIN,
         flv.LAST_UPDATE_DATE                ORA_LOOKUP_EMR_BRANCH_AREA_MAPPING_MLS_LAST_UPDATE_DATE,
         flv.SOURCE_LANG                     ORA_LOOKUP_EMR_BRANCH_AREA_MAPPING_MLS_SOURCE_LANG,
         flv.SECURITY_GROUP_ID               ORA_LOOKUP_EMR_BRANCH_AREA_MAPPING_MLS_SECURITY_GROUP_ID,
         flv.VIEW_APPLICATION_ID             ORA_LOOKUP_EMR_BRANCH_AREA_MAPPING_MLS_VIEW_APPLICATION_ID,
         flv.TERRITORY_CODE                  ORA_LOOKUP_EMR_BRANCH_AREA_MAPPING_MLS_TERRITORY_CODE,
         flv.ATTRIBUTE_CATEGORY              ORA_LOOKUP_EMR_BRANCH_AREA_MAPPING_MLS_ATTRIBUTE_CATEGORY,
         flv.ATTRIBUTE1                      ORA_LOOKUP_EMR_BRANCH_AREA_MAPPING_MLS_ATTRIBUTE1,
         flv.ATTRIBUTE2                      ORA_LOOKUP_EMR_BRANCH_AREA_MAPPING_MLS_ATTRIBUTE2,
         flv.ATTRIBUTE3                      ORA_LOOKUP_EMR_BRANCH_AREA_MAPPING_MLS_ATTRIBUTE3,
         flv.ATTRIBUTE4                      ORA_LOOKUP_EMR_BRANCH_AREA_MAPPING_MLS_ATTRIBUTE4,
         flv.ATTRIBUTE5                      ORA_LOOKUP_EMR_BRANCH_AREA_MAPPING_MLS_ATTRIBUTE5,
         flv.ATTRIBUTE6                      ORA_LOOKUP_EMR_BRANCH_AREA_MAPPING_MLS_ATTRIBUTE6,
         flv.ATTRIBUTE7                      ORA_LOOKUP_EMR_BRANCH_AREA_MAPPING_MLS_ATTRIBUTE7,
         flv.ATTRIBUTE8                      ORA_LOOKUP_EMR_BRANCH_AREA_MAPPING_MLS_ATTRIBUTE8,
         flv.ATTRIBUTE9                      ORA_LOOKUP_EMR_BRANCH_AREA_MAPPING_MLS_ATTRIBUTE9,
         flv.ATTRIBUTE10                     ORA_LOOKUP_EMR_BRANCH_AREA_MAPPING_MLS_ATTRIBUTE10,
         flv.ATTRIBUTE11                     ORA_LOOKUP_EMR_BRANCH_AREA_MAPPING_MLS_ATTRIBUTE11,
         flv.ATTRIBUTE12                     ORA_LOOKUP_EMR_BRANCH_AREA_MAPPING_MLS_ATTRIBUTE12,
         flv.ATTRIBUTE13                     ORA_LOOKUP_EMR_BRANCH_AREA_MAPPING_MLS_ATTRIBUTE13,
         flv.ATTRIBUTE14                     ORA_LOOKUP_EMR_BRANCH_AREA_MAPPING_MLS_ATTRIBUTE14,
         flv.ATTRIBUTE15                     ORA_LOOKUP_EMR_BRANCH_AREA_MAPPING_MLS_ATTRIBUTE15,
         flv.TAG                             ORA_LOOKUP_EMR_BRANCH_AREA_MAPPING_MLS_TAG,
         flv.LEAF_NODE                       ORA_LOOKUP_EMR_BRANCH_AREA_MAPPING_MLS_LEAF_NODE,
         flv.ZD_EDITION_NAME                 ORA_LOOKUP_EMR_BRANCH_AREA_MAPPING_MLS_ZD_EDITION_NAME,
         flv.ZD_SYNC                         ORA_LOOKUP_EMR_BRANCH_AREA_MAPPING_MLS_ZD_SYNC,
         flv.FETCH_DATE                      ORA_LOOKUP_EMR_BRANCH_AREA_MAPPING_MLS_FETCH_DATE,
         ag.WAGAGT                           AS400_AGENT,
         ag.WAGLBAGT                         AS400_AGENT_LIBELLE,
         ag.WAGMTV                           AS400_METIER_VENTE,
         ag.WAGSUC                           AS400_SUCCURSALE,
         su.WSULBSUC                         AS400_SUCCURSALE_LIBELLE,
         su.WSUREG                           AS400_REGION,
         rg.WRGLBREG                         AS400_REGION_LIBELLE,
         rg.WRGMAR                           AS400_MARCHE,
         mr.WMRLBMAR                         AS400_MARCHE_LIBELLE,
         mr.FETCH_DATE                       AS400_FETCH_DATE ,
         rownum                              ROW_NUMBER_ID,
         sysdate                             ROW_CREATION_DATE ,
         sysdate                             ROW_LAST_UPDATE_DATE,
         to_char(jrs.salesrep_id)            ORA_SALESREP_SALESREP_IDA
      FROM DEV.LH2_BRONZE_DEV.steph_apps_JTF_RS_SALESREPS jrs
      LEFT OUTER JOIN DEV.LH2_BRONZE_DEV.steph_apps_JTF_RS_DEFRESOURCES_V jrd
         ON jrs.resource_id = jrd.resource_id
      LEFT OUTER JOIN DEV.LH2_BRONZE_DEV.steph_apps_FND_LOOKUP_VALUES flv
         ON jrd.attribute1 = flv.lookup_code
         AND jrd.ATTRIBUTE_CATEGORY in ('LEROY SOMER', 'EIA')
         AND flv.LANGUAGE = 'US'
         AND flv.LOOKUP_TYPE = 'EMR BRANCH AREA MAPPING MLS'
      LEFT OUTER JOIN DEV.LH2_BRONZE_DEV.siege_lbprddwh_pfwag ag
         ON jrs.salesrep_number = to_char(ag.wagagt)
      LEFT OUTER JOIN DEV.LH2_BRONZE_DEV.siege_lbprddwh_pfwsu su
         ON ag.wagsuc = su.wsusuc
      LEFT OUTER JOIN DEV.LH2_BRONZE_DEV.siege_lbprddwh_pfwrg rg
         ON su.wsureg = rg.wrgreg
      LEFT OUTER JOIN DEV.LH2_BRONZE_DEV.siege_lbprddwh_pfwmr mr
         ON rg.wrgmar = mr.wmrmar
